// Generates a real on-disk `.d.ts` for a `.module.css` (or `.module.scss`/`.module.less`/
// `.module.styl`) file — the follow-up the symbiote-sfc-style-compiler skill records as
// deliberately deferred when CSS Modules shipped. Unlike Volar's built-in `<style module>`
// typing for inline Vue SFC blocks (which synthesizes `Record<string, string> & {known keys}` —
// an index signature that still accepts any key, so it never catches a typo), the type emitted
// here has NO index signature: a typo in `styles.typo` is a genuine `error TS2339` under `tsc`/
// `vue-tsc`, not a silent runtime miss. Named `<file>.d.ts` (full original filename, extension
// appended rather than replaced — e.g. `Card.module.css.d.ts`) so TypeScript's own module
// resolution picks it up for `import styles from './Card.module.css'` without a separate
// registration step, the same convention typed-css-modules uses.
import { parseCSS } from './parser.ts';
import { compile, detectLanguage } from './preprocessors.ts';
import { isCssModuleFile } from './metro-css-module.ts';

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function formatKey(className: string): string {
  return IDENTIFIER_RE.test(className) ? className : JSON.stringify(className);
}

export function classNamesToDtsSource(classNames: readonly string[]): string {
  const fields = [...classNames]
    .sort()
    .map(className => `  readonly ${formatKey(className)}: string;`)
    .join('\n');

  return [
    '// Auto-generated by @symbiote/css-parser from the matching CSS Modules file.',
    '// Do not edit by hand — regenerate via `css-dts` instead.',
    'declare const styles: {',
    fields,
    '};',
    'export default styles;',
    '',
  ].join('\n');
}

// Mirrors compileCssFile's own module/non-module branch: a plain (non-`.module.*`) style file
// has no default export to type (registerStyles() runs as a side effect only), so it gets no
// `.d.ts` at all.
export async function generateModuleDts(source: string, filename: string): Promise<string | null> {
  if (!isCssModuleFile(filename)) return null;

  const lang = detectLanguage(filename);
  const css = lang === 'css' ? source : await compile(source, lang, filename);
  const parsed = parseCSS(css, { filename });

  return classNamesToDtsSource(Object.keys(parsed));
}
