// Side-effect: register RNSScreen/RNSScreenStack/RNSScreenStackHeaderConfig/
// RNSScreenStackHeaderSubview/RNSSearchBar/RNSScreenContentWrapper's ViewConfigs in RN's
// ReactNativeViewConfigRegistry. Evaluating each codegen native-component spec
// (codegenNativeComponent('RNSScreen', ...) etc.) registers the getter the engine reads via
// setNativeViewConfigSource, so events + color processors derive on first commit. We import the
// codegen SPECS, never react-native-screens' React components (ScreenStack.tsx et al - hooks,
// crashes a non-React adapter) - these modules have no hooks, so they are framework-agnostic and
// shared by every adapter entry. Each adapter barrel imports this; the component modules and
// their headless tests stay free of it. See CLAUDE.md <third_party_rn_packages_are_react_only>.
//
// RNSSearchBar (headerSearchBarOptions' native leaf, nested by render-stack.ts's
// renderHeaderConfig) was missing from this list - its ViewConfig was never registered, so Fabric
// had no component descriptor for 'RNSSearchBar' and crashed on mount the moment a screen set
// headerSearchBarOptions. That is the root cause of the search-bar crash, not a deeper
// Fabric-interop gap.
//
// RNSScreenStackHeaderSubview (the wrapper renderHeaderConfig nests the search bar leaf inside,
// per RNSScreenStackHeaderConfig.mm's mountChildComponentView requiring every header child to be
// one) needs the same registration, or the same class of mount crash follows.
//
// RNSScreenContentWrapper (the RNS_SCREEN_CONTENT_WRAPPER_VIEW_NAME wrapper stack.ts wraps every
// screen's content in - see its comment in core/constants.ts) additionally needs a NATIVE-side
// registration: this file alone is not enough. The native iOS registry
// (RCTThirdPartyComponentsProvider.mm, generated by codegen from THIS package's own
// package.json#codegenConfig.ios.componentProvider map, NOT from react-native-screens') has no
// entry for 'RNSScreenContentWrapper' by default, so without it Fabric falls back to its
// "Unimplemented component" placeholder view regardless of this file's import. Both registries
// are independently required for a never-before-used react-native-screens view: this file (JS
// ViewConfig, read by @symbiote-native/engine's registry.ts) and package.json's componentProvider
// map (native ComponentDescriptor, read by codegen at `pod install` time).
//
// RNSModalScreen's gap on both registries isn't a mount crash but a silent mispositioning bug.
// react-native-screens' own Screen.tsx picks
// ModalScreenNativeComponent ('RNSModalScreen') instead of ScreenNativeComponent ('RNSScreen')
// whenever stackPresentation isn't push/containedModal/containedTransparentModal, because
// RNSScreen.mm's updateLayoutMetrics: checks `[self isKindOfClass:RNSModalScreen.class]` and, for
// that class, DELIBERATELY skips applying Yoga's computed frame (its own comment: "the available
// space is most likely restricted & differs from what Yoga resolves during first layout - we want
// to rely on native layout here"). Emitting a plain 'RNSScreen' for a formSheet/modal presentation
// (as resolveScreenViewName below used to do unconditionally) means that check never matches, so
// Yoga's frame - computed as if the screen were still a normal flexed sibling in its outer
// RNSScreenStack's push-oriented column layout - gets applied verbatim and never corrected,
// visually shifting the whole modal down by one full screen's height. Fixed in
// core/render-stack.ts's resolveScreenViewName, which now mirrors Screen.tsx's own
// shouldUseModalScreenComponent condition exactly.
//
// Unlike @symbiote-native/slider (which deep-imports @react-native-community/slider's compiled
// `dist/`), react-native-screens declares `"react-native": "src/index"` in its package.json -
// Metro's resolverMainFields prioritizes that field, so it resolves the library straight to raw
// TypeScript source and transforms it like first-party code. The deep import below targets that
// same `src/fabric/` tree rather than a compiled output.

import 'react-native-screens/src/fabric/ScreenNativeComponent';
import 'react-native-screens/src/fabric/ModalScreenNativeComponent';
import 'react-native-screens/src/fabric/ScreenStackNativeComponent';
import 'react-native-screens/src/fabric/ScreenStackHeaderConfigNativeComponent';
import 'react-native-screens/src/fabric/ScreenStackHeaderSubviewNativeComponent';
import 'react-native-screens/src/fabric/SearchBarNativeComponent';
import 'react-native-screens/src/fabric/ScreenContentWrapperNativeComponent';
