// TabRouter: the logic half (framework-agnostic, zero render). A pure reducer over a FOCUSED
// INDEX into a fixed route list - jumpTo/setParams - mirroring what @react-navigation/routers'
// TabRouter keeps, minus the React-specific action-creator/linking machinery. The key structural
// difference from navigator-state's Stack: tabs never push/pop a route, they move a focused
// index between a fixed set (mirrors TabRouter.getInitialState / getStateForAction for
// JUMP_TO - see the tab-actions docs: jumpTo takes a route NAME, not a stack push). Route
// identity (`key`) is generated by the CALLER, same convention as navigator-state.ts - reused
// verbatim from there so Stack and Tabs share one route shape.

import { mergeParams } from '../guards';
import type { IRoute } from '../navigator-state';

export type { IRoute } from '../navigator-state';

type IRouteEntry = IRoute<unknown>;

export type ITabRouterState = Readonly<{
  routes: readonly IRouteEntry[];
  index: number;
}>;

export type ITabRouterAction =
  | { type: 'jumpTo'; name: string; params?: unknown }
  | { type: 'setParams'; key: string; params: unknown };

const INITIAL_FOCUSED_INDEX = 0;

export function createInitialTabState(
  routes: readonly IRouteEntry[],
  initialRouteName?: string,
): ITabRouterState {
  if (initialRouteName === undefined) return { routes, index: INITIAL_FOCUSED_INDEX };
  const index = routes.findIndex(route => route.name === initialRouteName);
  return { routes, index: index === -1 ? INITIAL_FOCUSED_INDEX : index };
}

// jumpTo moves the focused index to an existing route by name and optionally merges params
// (navigation.jumpTo(name, params) - the tab-actions doc's own signature); it never adds,
// removes, or reorders routes (mirrors TabRouter: JUMP_TO is a no-op when the target name isn't
// registered, same as navigatorReducer's popTo bailing on an unknown key). setParams merges into
// the target route's params by key (CommonActions.setParams semantics - a merge, not a replace).
export function tabRouterReducer(
  state: ITabRouterState,
  action: ITabRouterAction,
): ITabRouterState {
  switch (action.type) {
    case 'jumpTo': {
      const index = state.routes.findIndex(route => route.name === action.name);
      if (index === -1) return state;
      if (action.params === undefined) {
        return index === state.index ? state : { ...state, index };
      }
      const target = state.routes[index];
      const routes = state.routes.slice();
      routes[index] = { ...target, params: mergeParams(target.params, action.params) };
      return { ...state, index, routes };
    }

    case 'setParams': {
      const index = state.routes.findIndex(route => route.key === action.key);
      if (index === -1) return state;
      const target = state.routes[index];
      const routes = state.routes.slice();
      routes[index] = { ...target, params: mergeParams(target.params, action.params) };
      return { ...state, routes };
    }

    default:
      return state;
  }
}

export function isFocusedRoute(index: number, focusedIndex: number): boolean {
  return index === focusedIndex;
}
