// Navigator: the logic half (framework-agnostic, zero render). A pure reducer over a route
// stack - push/pop/popToTop/popTo/replace - mirroring what @react-navigation/native-stack keeps
// in its router, minus the React-specific action-creator/linking machinery. Route identity
// (`key`) is generated by the CALLER (the adapter, via React's useId or an equivalent) - the
// reducer never invents identity itself, so it stays a pure (state, action) => state function.

import { SCREEN_ACTIVITY_STATE_FOCUSED, SCREEN_ACTIVITY_STATE_INACTIVE } from '../constants';
import { mergeParams } from '../guards';

export type IRoute<TParams = undefined> = Readonly<{
  key: string;
  name: string;
  params: TParams;
}>;

type IRouteEntry = IRoute<unknown>;

export type INavigatorState = Readonly<{
  routes: readonly IRouteEntry[];
}>;

export type INavigatorAction =
  | { type: 'push'; route: IRouteEntry }
  | { type: 'pop'; count?: number }
  | { type: 'popToTop' }
  | { type: 'popTo'; key: string }
  | { type: 'replace'; route: IRouteEntry }
  | { type: 'setParams'; key?: string; params: unknown }
  | { type: 'reset'; state: INavigatorState };

export function createInitialNavigatorState(initialRoute: IRouteEntry): INavigatorState {
  return { routes: [initialRoute] };
}

// The stack never pops its last route - mirrors the library refusing to pop the initial screen;
// the caller (e.g. a hardware back handler) decides what a pop-at-root means for the host app.
export function navigatorReducer(
  state: INavigatorState,
  action: INavigatorAction,
): INavigatorState {
  switch (action.type) {
    case 'push':
      return { routes: [...state.routes, action.route] };

    case 'pop': {
      if (state.routes.length <= 1) return state;
      const count = action.count ?? 1;
      const nextLength = Math.max(1, state.routes.length - count);
      return { routes: state.routes.slice(0, nextLength) };
    }

    case 'popToTop':
      return state.routes.length <= 1 ? state : { routes: state.routes.slice(0, 1) };

    case 'popTo': {
      const index = state.routes.findIndex(route => route.key === action.key);
      if (index === -1) return state;
      return { routes: state.routes.slice(0, index + 1) };
    }

    case 'replace': {
      if (state.routes.length === 0) return { routes: [action.route] };
      return { routes: [...state.routes.slice(0, -1), action.route] };
    }

    // Mirrors @react-navigation's CommonActions.setParams: merges onto the route matched by
    // `key`, defaulting to the focused (top-of-stack) route when omitted - same shape as its
    // `source`-defaults-to-focused-route behavior, minus the cross-navigator target routing this
    // single-navigator reducer has no need for.
    case 'setParams': {
      const targetKey = action.key ?? state.routes[state.routes.length - 1]?.key;
      if (targetKey === undefined) return state;
      const index = state.routes.findIndex(route => route.key === targetKey);
      if (index === -1) return state;
      const target = state.routes[index];
      const nextRoute: IRouteEntry = {
        ...target,
        params: mergeParams(target.params, action.params),
      };
      return {
        routes: [...state.routes.slice(0, index), nextRoute, ...state.routes.slice(index + 1)],
      };
    }

    // Mirrors @react-navigation's CommonActions.reset / BaseRouter's RESET handler: the payload
    // state replaces the current one verbatim, no merge - full rehydration (e.g. restoring a
    // persisted stack) is just a reset with the deserialized state as the payload.
    case 'reset':
      return action.state;

    default:
      return state;
  }
}

// Mirrors @react-navigation/native-stack's actual algorithm (NativeStackView.native.tsx:
// `activityState={isInactive ? 0 : 2}`, where isInactive = index > state.index) - NOT a
// three-way top/one-below/rest split. A route index beyond the focused one only exists for a
// preloaded-but-not-yet-navigated-to screen, a feature this reducer doesn't implement, so the
// focused index is always routesLength - 1 (the last route) and every currently-mounted route is
// FOCUSED. This is required, not just simpler: react-native-screens' native RNSScreen.mm asserts
// an already-mounted NativeStack screen's activityState can never decrease via a plain prop
// update ("activityState can only progress in NativeStack") - since no mounted route's index ever
// exceeds routesLength - 1, this formula never produces a decrease across a push or pop.
export function computeActivityState(index: number, routesLength: number): number {
  const focusedIndex = routesLength - 1;
  return index > focusedIndex ? SCREEN_ACTIVITY_STATE_INACTIVE : SCREEN_ACTIVITY_STATE_FOCUSED;
}

export function isTopRoute(index: number, routesLength: number): boolean {
  return index === routesLength - 1;
}
